# Author: Abdelrahman Hany
# Created on: 18-Feb-2022

name: React Application

on:
  pull_request:
    branches: [ beta ]

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        npm i
        npm run build --if-present

    #- name: Run the tests and generate coverage report
      #run: npm test -- --coverage
    #- name: Codecov
      #uses: codecov/codecov-action@v2.1.0
